// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subconscious.Engine.Data;

#nullable disable

namespace Subconscious.Engine.Data.Migrations
{
    [DbContext(typeof(SubconsciousDbContext))]
    partial class SubconsciousDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.AppState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT")
                        .HasColumnName("client");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Tag", "Client")
                        .IsUnique()
                        .HasDatabaseName("uq_app_state_key_tag_client");

                    b.ToTable("app_state", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("Embedding")
                        .HasColumnType("TEXT")
                        .HasColumnName("embedding");

                    b.Property<int?>("EndLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_line");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<int?>("StartLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_line");

                    b.Property<int?>("TokenEstimate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_estimate");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.IndexedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("Directory")
                        .HasColumnType("TEXT")
                        .HasColumnName("directory");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<int?>("Mtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mtime");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int?>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("indexed_documents", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thread_id");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultWorkspaceUuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_workspace_uuid");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("Passphrase")
                        .HasColumnType("BLOB")
                        .HasColumnName("passphrase");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.SkillRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InstallPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("install_path");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RequiredTools")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_tools");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("skill_registry", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultModelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_model_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("SkillsConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("skills_config");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("ToolsConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("tools_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("threads", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thread_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("todo_items", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.ToolRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("AuthEnvVar")
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_env_var");

                    b.Property<string>("AuthType")
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ScriptLanguage")
                        .HasColumnType("TEXT")
                        .HasColumnName("script_language");

                    b.Property<string>("ScriptPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("script_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("tool_registry", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultModelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_model_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Directories")
                        .HasColumnType("TEXT")
                        .HasColumnName("directories");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("network_id");

                    b.Property<string>("RagConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("rag_config");

                    b.Property<string>("SkillsConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("skills_config");

                    b.Property<string>("ToolsConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("tools_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.WorkspaceMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int?>("SourceThreadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_thread_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceThreadId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("workspace_memory", (string)null);
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Contact", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("Contacts")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.IndexedDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.IndexedDocument", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("IndexedDocuments")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Message", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Thread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Note", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("Notes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Thread", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("Threads")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.TodoItem", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Thread", "Thread")
                        .WithMany("TodoItems")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("TodoItems")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Workspace", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Network", "Network")
                        .WithMany("Workspaces")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.WorkspaceMemory", b =>
                {
                    b.HasOne("Subconscious.Engine.Data.Entities.Thread", "SourceThread")
                        .WithMany("Memories")
                        .HasForeignKey("SourceThreadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Subconscious.Engine.Data.Entities.Workspace", "Workspace")
                        .WithMany("Memories")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceThread");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.IndexedDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Network", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Thread", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Messages");

                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("Subconscious.Engine.Data.Entities.Workspace", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("IndexedDocuments");

                    b.Navigation("Memories");

                    b.Navigation("Notes");

                    b.Navigation("Threads");

                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
