using System.Collections.Concurrent;

namespace Subconscious.Engine.Api.Sessions;

/// <summary>
/// Represents an active agent session connected to the engine.
/// Each client (VS Code extension, browser extension, desktop app, etc.) gets one session.
/// </summary>
public class AgentSession
{
    /// <summary>
    /// Unique session identifier generated by the engine on connection.
    /// </summary>
    public required string SessionId { get; init; }

    /// <summary>
    /// Client-provided identifier from client.hello frame. Null until hello received.
    /// </summary>
    public string? ClientId { get; set; }

    /// <summary>
    /// WebSocket connection for this session. Null for REST-only clients.
    /// </summary>
    public System.Net.WebSockets.WebSocket? WebSocket { get; set; }

    /// <summary>
    /// Execution profile set via profile.set frame.
    /// Defines workspace/thread context and tool configuration.
    /// </summary>
    public ExecutionProfile? Profile { get; set; }

    /// <summary>
    /// When this session was established.
    /// </summary>
    public DateTime ConnectedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Last activity timestamp for timeout detection.
    /// Updated on every frame sent or received.
    /// </summary>
    public DateTime LastActivityAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Tools registered by this client via tool.register frames.
    /// Key: tool_name, Value: tool registration metadata
    /// </summary>
    public ConcurrentDictionary<string, ToolRegistration> RegisteredTools { get; init; } = new();

    /// <summary>
    /// Cancellation token source for coordinated disconnect.
    /// Can be triggered by client disconnect, server shutdown, or timeout.
    /// </summary>
    public CancellationTokenSource DisconnectToken { get; init; } = new();

    /// <summary>
    /// Additional session metadata (e.g., user agent, client version, etc.)
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();

    /// <summary>
    /// Register a client-provided tool for this session.
    /// </summary>
    public void RegisterClientTool(string name, string description, object? schema = null)
    {
        var registration = new ToolRegistration
        {
            ToolId = $"client.{name}",
            Name = name,
            Description = description,
            Schema = schema ?? new { },
            RegisteredAt = DateTime.UtcNow
        };

        RegisteredTools.TryAdd(name, registration);
        LastActivityAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Get all available tools for this session (built-in + client-registered).
    /// </summary>
    public IEnumerable<string> GetAvailableTools()
    {
        // TODO: Add built-in tool names from ToolRegistry
        var builtInTools = new[] { "get_current_time", "get_weather", "calculate" };
        var clientTools = RegisteredTools.Keys;
        
        return builtInTools.Concat(clientTools);
    }

    /// <summary>
    /// Set a metadata key-value pair.
    /// </summary>
    public void SetMetadata(string key, string value)
    {
        Metadata[key] = value;
        LastActivityAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Get a metadata value, or null if not set.
    /// </summary>
    public string? GetMetadata(string key)
    {
        return Metadata.TryGetValue(key, out var value) ? value : null;
    }
}

/// <summary>
/// Execution profile from profile.set frame.
/// Defines the workspace/thread context and configuration for tool execution.
/// </summary>
public record ExecutionProfile
{
    public required string WorkspaceUuid { get; init; }
    public string? ThreadUuid { get; init; }
    public string? ModelId { get; init; }
    public Dictionary<string, object>? ToolsConfig { get; init; }
    public Dictionary<string, object>? SkillsConfig { get; init; }
}

/// <summary>
/// Metadata about a tool registered by a client.
/// </summary>
public record ToolRegistration
{
    public required string ToolId { get; init; }
    public required string Name { get; init; }
    public string? Description { get; init; }
    public required object Schema { get; init; }
    public DateTime RegisteredAt { get; init; } = DateTime.UtcNow;
}
